// import styles
import './globals.scss'
// import components
import Header from '@/components/header'
import Footer from '@/components/footer'
import { Providers } from './store/provider';
export const metadata = {
  title: 'Shop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body>
        <Providers>
          <div style={{ minHeight: "100vh", display: "flex", flexDirection: "column" }}>
            <Header key="header" />
            <main style={{flex: "1 1 auto"}}>{children}</main>
            <Footer key="footer" />
          </div>
        </Providers>
      </body>

    </html>
  )
}
